# Generated by Django 5.0.1 on 2024-01-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_fabric_category_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='price',
            field=models.IntegerField(),
        ),
    ]
